
export enum Abilities {
  Normal = "uabi",
  DefaultActiveAbility = "udaa",
  Hero = "uhab",
}

export enum Art {
  RequiredAnimationNames = "uani",
  IconGameInterface = "uico",
  RequiredAnimationNamesAttachments = "uaap",
  RequiredAttachmentLinkNames = "ualp",
  RequiredBoneNames = "ubpr",
  ButtonPositionX = "ubpx",
  ButtonPositionY = "ubpy",
  CasterUpgradeArt = "ucua",
  IconScoreScreen = "ussi",
  Special = "uspa",
  Target = "utaa",
  DeathTimeseconds = "udtm",
  UseExtendedLineofSight = "ulos",
  OrientationInterpolation = "uori",
  PropulsionWindowdegrees = "uprw",
  AnimationBlendTimeseconds = "uble",
  TintingColor3Blue = "uclb",
  ShadowTextureBuilding = "ushb",
  AllowCustomTeamColor = "utcc",
  ElevationSamplePoints = "uept",
  ElevationSampleRadius = "uerd",
  ModelFile = "umdl",
  ModelFileExtraVersions = "uver",
  FogofWarSampleRadius = "ufrd",
  TintingColor2Green = "uclg",
  MaximumPitchAngledegrees = "umxp",
  MaximumRollAngledegrees = "umxr",
  ScalingValue = "usca",
  OccluderHeight = "uocc",
  TintingColor1Red = "uclr",
  AnimationRunSpeed = "urun",
  SelectionScale = "ussc",
  ScaleProjectiles = "uscb",
  SelectionCircleOnWater = "usew",
  SelectionCircleHeight = "uslz",
  ShadowImageHeight = "ushh",
  HasWaterShadow = "ushr",
  ShadowImageWidth = "ushw",
  ShadowImageCenterX = "ushx",
  ShadowImageCenterY = "ushy",
  TeamColor = "utco",
  GroundTexture = "uubs",
  ShadowImageUnit = "ushu",
  AnimationWalkSpeed = "uwal",
  AnimationCastBackswing = "ucbs",
  AnimationCastPoint = "ucpt",
  ProjectileImpactZSwimming = "uisz",
  ProjectileImpactZ = "uimz",
  ProjectileLaunchZSwimming = "ulsz",
  ProjectileLaunchX = "ulpx",
  ProjectileLaunchY = "ulpy",
  ProjectileLaunchZ = "ulpz",
}

export enum Combat {
  Attack1ProjectileArc = "uma1",
  Attack2ProjectileArc = "uma2",
  Attack1ProjectileArt = "ua1m",
  Attack2ProjectileArt = "ua2m",
  Attack1ProjectileHomingEnabled = "umh1",
  Attack2ProjectileHomingEnabled = "umh2",
  Attack1ProjectileSpeed = "ua1z",
  Attack2ProjectileSpeed = "ua2z",
  DefenseBase = "udef",
  DefenseType = "udty",
  DefenseUpgradeBonus = "udup",
  DeathTimeseconds = "udea",
  TargetedAs = "utar",
  ArmorType = "uarm",
  AcquisitionRange = "uacq",
  Attack1AttackType = "ua1t",
  Attack2AttackType = "ua2t",
  Attack1AnimationBackswingPoint = "ubs1",
  Attack2AnimationBackswingPoint = "ubs2",
  Attack1CooldownTime = "ua1c",
  Attack2CooldownTime = "ua2c",
  Attack1DamageLossFactor = "udl1",
  Attack2DamageLossFactor = "udl2",
  Attack1DamageNumberofDice = "ua1d",
  Attack2DamageNumberofDice = "ua2d",
  Attack1DamageBase = "ua1b",
  Attack2DamageBase = "ua2b",
  Attack1AnimationDamagePoint = "udp1",
  Attack2AnimationDamagePoint = "udp2",
  Attack1DamageUpgradeAmount = "udu1",
  Attack2DamageUpgradeAmount = "udu2",
  Attack1AreaofEffectFullDamage = "ua1f",
  Attack2AreaofEffectFullDamage = "ua2f",
  Attack1AreaofEffectMediumDamage = "ua1h",
  Attack2AreaofEffectMediumDamage = "ua2h",
  Attack1DamageFactorMedium = "uhd1",
  Attack2DamageFactorMedium = "uhd2",
  MinimumAttackRange = "uamn",
  Attack1AreaofEffectSmallDamage = "ua1q",
  Attack2AreaofEffectSmallDamage = "ua2q",
  Attack1DamageFactorSmall = "uqd1",
  Attack2DamageFactorSmall = "uqd2",
  Attack1Range = "ua1r",
  Attack2Range = "ua2r",
  Attack1RangeMotionBuffer = "urb1",
  Attack2RangeMotionBuffer = "urb2",
  Attack1ShowUI = "uwu1",
  Attack2ShowUI = "uwu2",
  Attack1DamageSidesperDie = "ua1s",
  Attack2DamageSidesperDie = "ua2s",
  Attack1DamageSpillDistance = "usd1",
  Attack2DamageSpillDistance = "usd2",
  Attack1DamageSpillRadius = "usr1",
  Attack2DamageSpillRadius = "usr2",
  Attack1AreaofEffectTargets = "ua1p",
  Attack2AreaofEffectTargets = "ua2p",
  Attack1MaximumNumberofTargets = "utc1",
  Attack2MaximumNumberofTargets = "utc2",
  Attack1TargetsAllowed = "ua1g",
  Attack2TargetsAllowed = "ua2g",
  AttacksEnabled = "uaen",
  Attack1WeaponType = "ua1w",
  Attack2WeaponType = "ua2w",
  Attack1WeaponSound = "ucs1",
  Attack2WeaponSound = "ucs2",
}

export enum Editor {
  Tilesets = "util",
  CategorizationCampaign = "ucam",
  CanDropItemsOnDeath = "udro",
  DisplayasNeutralHostile = "uhos",
  PlaceableInEditor = "uine",
  CategorizationSpecial = "uspe",
  HasTilesetSpecificData = "utss",
  UseClickHelper = "uuch",
}

export enum Movement {
  SpeedMaximum = "umas",
  SpeedMinimum = "umis",
  GroupSeparationEnabled = "urpo",
  GroupSeparationGroupNumber = "urpg",
  GroupSeparationParameter = "urpp",
  GroupSeparationPriority = "urpr",
  SpeedBase = "umvs",
  HeightMinimum = "umvf",
  Height = "umvh",
  Type = "umvt",
  TurnRate = "umvr",
}

export enum Pathing {
  CollisionSize = "ucol",
  PlacementRequires = "upap",
  PlacementPreventedBy = "upar",
  AIPlacementRadius = "uabr",
  AIPlacementType = "uabt",
  PathingMap = "upat",
  PlacementRequiresWaterRadius = "upaw",
}

export enum Sound {
  Construction = "ubsl",
  LoopingFadeInRate = "ulfi",
  LoopingFadeOutRate = "ulfo",
  Movement = "umsl",
  Random = "ursl",
  UnitSoundSet = "usnd",
}

export enum Stats {
  StartingAgility = "uagi",
  AgilityperLevel = "uagp",
  BuildTime = "ubld",
  GoldBountyAwardedNumberofDice = "ubdi",
  GoldBountyAwardedBase = "ubba",
  GoldBountyAwardedSidesperDie = "ubsi",
  LumberBountyAwardedNumberofDice = "ulbd",
  LumberBountyAwardedBase = "ulba",
  LumberBountyAwardedSidesperDie = "ulbs",
  FoodProduced = "ufma",
  FoodCost = "ufoo",
  GoldCost = "ugol",
  RepairGoldCost = "ugor",
  HitPointsMaximumBase = "uhpm",
  StartingIntelligence = "uint",
  IntelligenceperLevel = "uinp",
  IsaBuilding = "ubdg",
  Level = "ulev",
  LumberCost = "ulum",
  RepairLumberCost = "ulur",
  ManaInitialAmount = "umpi",
  ManaMaximum = "umpm",
  NeutralBuildingValidAsRandomBuilding = "unbr",
  SightRadiusNight = "usin",
  PrimaryAttribute = "upra",
  HitPointsRegenerationRate = "uhpr",
  ManaRegeneration = "umpr",
  HitPointsRegenerationType = "uhrt",
  RepairTime = "urtm",
  SightRadiusDay = "usid",
  StockMaximum = "usma",
  StockReplenishInterval = "usrg",
  StockStartDelay = "usst",
  StartingStrength = "ustr",
  StrengthperLevel = "ustp",
  UnitClassification = "utyp",
  CanBuildOn = "ucbo",
  CanFlee = "ufle",
  CanSleep = "usle",
  TransportedSize = "ucar",
  FormationRank = "ufor",
  CanBeBuiltOn = "uibo",
  PointValue = "upoi",
  Priority = "upri",
  Race = "urac",
  NeutralBuildingShowsMinimapIcon = "unbm",
  HeroHideHeroInterfaceIcon = "uhhb",
  HeroHideHeroMinimapDisplay = "uhhm",
  HeroHideHeroDeathMessage = "uhhd",
  HideMinimapDisplay = "uhom",
}

export enum Techtree {
  StructuresBuilt = "ubui",
  DependencyEquivalents = "udep",
  ItemsMade = "umki",
  RequirementsTiersUsed = "urqc",
  Requirements = "ureq",
  RequirementsTier2 = "urq1",
  RequirementsTier3 = "urq2",
  RequirementsTier4 = "urq3",
  RequirementsTier5 = "urq4",
  RequirementsTier6 = "urq5",
  RequirementsTier7 = "urq6",
  RequirementsTier8 = "urq7",
  RequirementsTier9 = "urq8",
  RequirementsLevels = "urqa",
  ResearchesAvailable = "ures",
  RevivesDeadHeroes = "urev",
  ItemsSold = "usei",
  UnitsSold = "useu",
  UnitsTrained = "utra",
  HeroRevivalLocations = "urva",
  UpgradesTo = "uupt",
  UpgradesUsed = "upgr",
}

export enum Text {
  TooltipAwaken = "uawt",
  CasterUpgradeNames = "ucun",
  CasterUpgradeTips = "ucut",
  NameEditorSuffix = "unsf",
  Hotkey = "uhot",
  Name = "unam",
  ProperNames = "upro",
  TooltipRevive = "utpr",
  TooltipBasic = "utip",
  TooltipExtended = "utub",
  ProperNamesUsed = "upru",
}



enum Misc {
  HeroSkin = "",
  NormalSkin = "",
}

export const UnitFieldRawCodes = { 
  Abilities,
  Art,
  Combat,
  Editor,
  Movement,
  Pathing,
  Sound,
  Stats,
  Techtree,
  Text,
  Misc
};

export type UnitFieldRawCodes = typeof UnitFieldRawCodes;

export type UnitFieldRawCode = {
  [K in keyof UnitFieldRawCodes]: {
    [K2 in keyof UnitFieldRawCodes[K]]: UnitFieldRawCodes[K][K2]
  }[keyof UnitFieldRawCodes[K]]
}[keyof UnitFieldRawCodes];